import { readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const skillDirectory = resolve(scriptDirectory, "..");
const referencesDirectory = join(skillDirectory, "references");
const skillPath = join(skillDirectory, "SKILL.md");
const outputPath = join(skillDirectory, "runtime.generated.ts");

function normalizeNewlines(value) {
	return value.replace(/\r\n/g, "\n").trim();
}

function parseSkill(value) {
	const normalized = value.replace(/\r\n/g, "\n");
	const match = normalized.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
	if (!match) {
		throw new Error(`Invalid SKILL.md frontmatter: ${skillPath}`);
	}

	const frontmatter = Object.fromEntries(
		match[1]
			.split("\n")
			.map((line) => line.match(/^([a-zA-Z0-9_-]+):\s*(.*)$/))
			.filter(Boolean)
			.map((entry) => [entry[1], entry[2]]),
	);

	if (!frontmatter.name || !frontmatter.description) {
		throw new Error("SKILL.md requires name and description");
	}

	return {
		name: frontmatter.name,
		description: frontmatter.description,
		content: normalizeNewlines(match[2]),
	};
}

function serialize(value) {
	return JSON.stringify(value, null, "\t")
		.replace(/\u2028/g, "\\u2028")
		.replace(/\u2029/g, "\\u2029");
}

const skill = parseSkill(await readFile(skillPath, "utf8"));
const referenceNames = (await readdir(referencesDirectory))
	.filter((name) => name.endsWith(".md"))
	.sort((left, right) => left.localeCompare(right));

const resources = Object.fromEntries(
	await Promise.all(
		referenceNames.map(async (name) => [
			`references/${name}`,
			normalizeNewlines(await readFile(join(referencesDirectory, name), "utf8")),
		]),
	),
);

const banner = [
	"/*",
	" * Generated by scripts/generate_runtime_projection.mjs.",
	" * Edit SKILL.md or references/*.md, then regenerate this file.",
	" * Source: SKILL.md and references/*.md in this directory.",
	" */",
].join("\n");

const output = `${banner}

export const PREMIUM_VIDEO_EDITOR_RUNTIME_SKILL = ${serialize({
	...skill,
	resourceNames: Object.keys(resources),
})} as const;

export const PREMIUM_VIDEO_EDITOR_RUNTIME_RESOURCES: Readonly<
	Record<string, string>
> = ${serialize(resources)};
`;

if (process.argv.includes("--check")) {
	const existing = await readFile(outputPath, "utf8").catch(() => "");
	if (existing !== output) {
		throw new Error(
			`${relative(process.cwd(), outputPath)} is stale. Run generate_runtime_projection.mjs.`,
		);
	}
	console.log(
		`Verified ${relative(process.cwd(), outputPath)} is current (${referenceNames.length} resources).`,
	);
	process.exit(0);
}

await writeFile(outputPath, output, "utf8");
console.log(
	`Generated ${relative(process.cwd(), outputPath)} with ${referenceNames.length} resources.`,
);
