/** Bundle only official browser helpers plus our DOM adapter. */
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const root = new URL("../apps/web/src/hyperframes/", import.meta.url);
const core = dirname(Bun.resolveSync("@hyperframes/core", fileURLToPath(root)));
if (
	(await Bun.file(join(core, "..", "package.json")).json()).version !==
	"0.8.115"
)
	throw new Error(
		"Review the audio probe against the new HyperFrames version before rebuilding",
	);
const result = await Bun.build({
	entrypoints: [fileURLToPath(new URL("audio-probe.browser.ts", root))],
	target: "browser",
	format: "iife",
	minify: true,
	plugins: [
		{
			name: "pinned-public-media-render-ids",
			setup(build) {
				// The public root export also pulls in Node-only compiler code. Resolve
				// this one public helper to its unchanged implementation in 0.8.115.
				build.onResolve({ filter: /^@hyperframes\/core$/ }, () => ({
					path: join(core, "compiler", "mediaRenderIds.js"),
				}));
			},
		},
	],
});
if (!result.success)
	throw new AggregateError(result.logs, "HyperFrames audio probe build failed");
const bundle = await result.outputs[0].text();
await Bun.write(
	new URL("audio-probe.generated.ts", root),
	"// Generated by classic/scripts/build-hyperframes-audio-probe.ts. Do not edit.\n" +
		"// Contains @hyperframes/core 0.8.115, Apache-2.0. See THIRD-PARTY-NOTICES.md.\n" +
		`export const HYPERFRAMES_AUDIO_PROBE = ${JSON.stringify(bundle)};\n`,
);
console.log(`Built HyperFrames audio probe (${bundle.length} bytes)`);
