// Host packaging only. Editor documents continue to live in OpenCutRuntime.
import { spawn, execFileSync } from 'node:child_process';
import { cp, mkdir, readFile, writeFile, rm, access, symlink } from 'node:fs/promises';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { classicRoot, repository, deploymentRoot, configuration, writeJson, readJson, runtimeEnvironment } from './common.mjs';

const config = await configuration();
const environment = await runtimeEnvironment(config);
const webRoot = join(classicRoot, 'apps/web');
const buildDir = '.next-local-production';
const statusPath = join(deploymentRoot, 'build.json');
const lockPath = join(deploymentRoot, 'build.lock');
let ownsLock = false;
async function status(phase, extra = {}) {
  console.log(`[production] ${phase}`);
  await writeJson(statusPath, { phase, running: true, updatedAt: new Date().toISOString(), ...extra });
}
function run(command, args, cwd = classicRoot, extra = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, { cwd, stdio: 'inherit', detached: true, env: {
      ...environment, ...extra,
    } });
    const terminate = () => { try { process.kill(-child.pid, 'SIGTERM'); } catch {} };
    process.once('SIGTERM', terminate);
    child.once('error', reject);
    child.once('exit', (code, signal) => {
      process.removeListener('SIGTERM', terminate);
      code === 0 ? resolve() : reject(Error(`${command} failed (${code ?? signal})`));
    });
  });
}
async function sourceFingerprint() {
  const files = execFileSync('git', ['ls-files', '-z', '--cached', '--others', '--exclude-standard'], { cwd: repository }).toString().split('\0').filter(Boolean).sort();
  const hash = createHash('sha256');
  for (const file of files) {
    // next-env.d.ts is generated by Next, not application source.
    if (file.endsWith('/next-env.d.ts')) continue;
    if (!/^(classic\/(apps\/(web|electron\/app)|rust|packages|patches)\/|crates\/|resources\/|Cargo\.(toml|lock)$|classic\/(package\.json|bun\.lock)$)/.test(file)) continue;
    hash.update(file);
    try { hash.update(await readFile(join(repository, file))); }
    catch (error) { if (error.code === 'ENOENT') hash.update('deleted'); else throw error; }
  }
  return hash.digest('hex');
}

try {
  const stale = await readJson(lockPath);
  if (stale) {
    let alive = true;
    try { process.kill(stale.pid, 0); } catch { alive = false; }
    if (alive) throw Error('Another production build is already running.');
    await rm(lockPath);
  }
  await writeFile(lockPath, JSON.stringify({ pid: process.pid }), { flag: 'wx', mode: 0o600 });
  ownsLock = true;
  await status('Checking local source');
  const fingerprint = await sourceFingerprint();
  const commit = execFileSync('git', ['rev-parse', 'HEAD'], { cwd: repository }).toString().trim();
  const branch = execFileSync('git', ['branch', '--show-current'], { cwd: repository }).toString().trim();
  const dirty = !!execFileSync('git', ['status', '--porcelain'], { cwd: repository }).toString().trim();
  await status('Building canonical Rust / WASM');
  await run(config.bun, ['run', 'build:wasm']);
  await status('Preparing local assets');
  await run(config.node, ['scripts/prepare-hyperframes-references.mjs']);
  await run(config.node, ['scripts/verify-background-removal-assets.mjs'], webRoot);
  await status('Building local control plane');
  await run('cargo', ['build', '--release', '-p', 'opencut-mcp-server'], repository);
  await status('Building optimized production editor');
  await run(config.node, [join(webRoot, 'node_modules/next/dist/bin/next'), 'build', '--webpack'], webRoot, {
    NODE_ENV: 'production', OPENCUT_RUNTIME_TARGET: 'browser', OPENCUT_BUILD_DIR: buildDir,
  });
  if (await sourceFingerprint() !== fingerprint)
    throw Error('Source changed during the build. Current production was preserved; rebuild when editing is finished.');
  await status('Packaging standalone release');
  const id = `${new Date().toISOString().replace(/[:.]/g, '-')}-${commit.slice(0, 8)}`;
  const release = join(deploymentRoot, 'releases', id);
  await mkdir(release, { recursive: true, mode: 0o700 });
  await cp(join(webRoot, buildDir, 'standalone'), join(release, 'server'), { recursive: true, verbatimSymlinks: true });
  // Next's tracing root is classic/, so the standalone entry is apps/web/server.js.
  const appRoot = join(release, 'server/apps/web');
  await cp(join(webRoot, buildDir, 'static'), join(appRoot, buildDir, 'static'), { recursive: true });
  await cp(join(webRoot, 'public'), join(appRoot, 'public'), { recursive: true });
  await cp(join(classicRoot, 'apps/electron/app'), join(release, 'electron'), { recursive: true, dereference: true });
  await cp(join(repository, 'target/release/opencut-mcp'), join(release, 'opencut-mcp'));
  await cp(join(classicRoot, 'scripts/local-subject-framing'), join(release, 'server/scripts/local-subject-framing'), { recursive: true });
  const detector = join(classicRoot, '.local/subject-framing');
  try {
    await access(detector);
    await mkdir(join(release, 'server/.local'), { recursive: true });
    await symlink(detector, join(release, 'server/.local/subject-framing'));
  } catch (error) { if (error.code !== 'ENOENT') throw error; }
  // Pin the shell binary as well as its source to this release.
  const electronPackage = JSON.parse(await readFile(join(classicRoot, 'apps/electron/package.json'), 'utf8'));
  const { createRequire } = await import('node:module');
  const require = createRequire(join(classicRoot, 'apps/electron/package.json'));
  const electronBinary = require('electron');
  const electronApp = electronBinary.slice(0, electronBinary.indexOf('/Contents/MacOS/'));
  if (!electronApp.endsWith('.app')) throw Error('This local installer currently supports macOS.');
  await cp(electronApp, join(release, 'Electron.app'), { recursive: true, verbatimSymlinks: true });
  const metadata = { id, commit, branch, dirty, fingerprint, builtAt: new Date().toISOString(), appRoot,
    electronVersion: electronPackage.devDependencies.electron };
  await writeJson(join(release, 'release.json'), metadata);
  await status('Verifying production release');
  // Startup smoke check happens on an ephemeral port without touching accounts.
  const { createServer } = await import('node:net');
  const probe = createServer();
  await new Promise(resolve => probe.listen(0, '127.0.0.1', resolve));
  const port = probe.address().port;
  await new Promise(resolve => probe.close(resolve));
  const smoke = spawn(config.node, [join(appRoot, 'server.js')], { cwd: appRoot, stdio: 'inherit',
    env: { ...environment, NODE_ENV: 'production', PORT: String(port), HOSTNAME: '127.0.0.1',
      OPENCUT_ACCOUNTS_DIR: config.accountsRoot, NEXT_TELEMETRY_DISABLED: '1' } });
  try {
    let healthy = false;
    for (let attempt = 0; attempt < 90; attempt++) {
      if (smoke.exitCode !== null) break;
      try {
        const response = await fetch(`http://127.0.0.1:${port}/`, { signal: AbortSignal.timeout(1000) });
        if (response.ok) { healthy = true; break; }
      } catch {}
      await new Promise(resolve => setTimeout(resolve, 250));
    }
    if (!healthy) throw Error('Production startup smoke check failed; previous release retained.');
  } finally { smoke.kill('SIGTERM'); }
  // Atomic activation: a failed build never changes this pointer.
  const previous = await readJson(join(deploymentRoot, 'current.json'));
  if (previous) await writeJson(join(deploymentRoot, 'previous.json'), previous);
  await writeJson(join(deploymentRoot, 'current.json'), metadata);
  await status('Production ready', { running: false, release: metadata });
} catch (error) {
  console.error(error);
  if (ownsLock) await status('Build failed', { running: false, error: error.message });
  process.exitCode = 1;
} finally {
  if (ownsLock) await rm(lockPath, { force: true });
}
